# 基础镜像
FROM redis:6.0.8
# author
MAINTAINER bsin-paas

# 挂载目录
VOLUME /home/bsinpaas/docker/redis
# 创建目录
RUN mkdir -p /home/bsinpaas/redis
# 指定路径
WORKDIR /home/bsinpaas/redis
# 复制conf文件到路径
COPY ./conf/redis.conf /home/bsinpaas/docker/redis/redis.conf
