# 基础镜像
FROM  openjdk:11
# author
MAINTAINER bsin-paas

LABEL version=2.0.0

# 挂载目录
VOLUME /home/bsin-paas-os/server-apps/ai-agent
# 创建目录
RUN mkdir -p /home/bsin-paas-os/server-apps/ai-agent
# 指定路径
WORKDIR /home/bsin-paas-os/server-apps/ai-agent
# 复制jar文件到路径
COPY ./jar/ai-agent-server-2.0.0-SNAPSHOT.jar /home/bsin-paas-os/server-apps/ai-agent/ai-agent-server-2.0.0-SNAPSHOT.jar
#COPY ../../../../.env /home/bsin-paas-os/server-apps/ai-agent/.env
# 启动用户服务
ENTRYPOINT ["java","-jar","ai-agent-server-2.0.0-SNAPSHOT.jar"]
