// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
let options = {"masterHistoryType":"hash","base":"/bsin-ui-ai-admin/","apps":[{"name":"bsin-ui-upms","entry":"http://127.0.0.1:8003"}],"routes":[{"path":"/bsin-ui-upms","microApp":"bsin-ui-upms"}]};
export const getMasterOptions = () => options;
export const setMasterOptions = (newOpts) => options = ({ ...options, ...newOpts });
