# 基础镜像
FROM  openjdk:11
# author
MAINTAINER bsin-paas

# 挂载目录
VOLUME /home/bsin-paas-os/server-apps/upms
# 创建目录
RUN mkdir -p /home/bsin-paas-os/server-apps/upms
# 指定路径
WORKDIR /home/bsin-paas-os/server-apps/upms
# 复制jar文件到路径
COPY ./jar/upms-server-2.0.0-SNAPSHOT.jar /home/bsin-paas-os/server-apps/upms/upms-server-2.0.0-SNAPSHOT.jar
# 启动用户服务
ENTRYPOINT ["java","-jar","upms-server-2.0.0-SNAPSHOT.jar"]
