spring:
  #数据库配置
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${UPMS_MYSQL_DB_URL}?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
    username: ${UPMS_MYSQL_DB_USERNAME}
    password: ${UPMS_MYSQL_DB_PASSWORD}
  #redis
  redis:
    host: ${UPMS_REDIS_HOST}
    port: ${UPMS_REDIS_PORT}
    password: ${UPMS_REDIS_PASSWORD}
    database: ${UPMS_REDIS_DB}

shenyu:
  register:
    registerType: http #zookeeper #etcd #nacos #consul
    serverLists: ${SHENYU_REGISTER_SERVERLISTS} #localhost:2181 #http://localhost:2379 #localhost:8848
    props:
      username: ${SHENYU_REGISTER_PROPS_USERNAME}
      password: ${SHENYU_REGISTER_PROPS_PASSWORD}
  client:
    dubbo:
      props:
        contextPath: /upms
        appName: upms

dubbo:
  application:
    name: ${spring.application.name}
    # 注册行为：应用级别  可选值 interface、instance、all
    register-mode: interface
    qos-enable: false
  registry:
    address: ${DOUBBO_REGISTRY_ADDRESS}
    username: ${DOUBBO_REGISTRY_USERNAME}
    password: ${DOUBBO_REGISTRY_ADDRESS}
  protocol:
    name: dubbo
    port: -1
  scan:
    base-packages: me.flyray.bsin.server.impl
  provider:
    validation: true
    version: dev
  consumer:
    check: false
    version: dev