spring:
  #数据库配置
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${UPMS_MYSQL_DB_URL}?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
    username: ${UPMS_MYSQL_DB_USERNAME}
    password: ${UPMS_MYSQL_DB_PASSWORD}
  #redis
  redis:
    host: ${UPMS_REDIS_HOST}
    port: ${UPMS_REDIS_PORT}
    password: ${UPMS_REDIS_PASSWORD}
    database: ${UPMS_REDIS_DB}

shenyu:
  register:
    registerType: http #zookeeper #etcd #nacos #consul
    serverLists: ${BSIN_SHENYU_REGISTER_SERVERLISTS} #localhost:2181 #http://localhost:2379 #localhost:8848
    props:
      username: ${BSIN_SHENYU_REGISTER_PROPS_USERNAME}
      password: ${BSIN_SHENYU_REGISTER_PROPS_PASSWORD}
  client:
    dubbo:
      props:
        contextPath: /upms
        appName: upms

dubbo:
  application:
    name: ${spring.application.name}
    # 注册行为：应用级别  可选值 interface、instance、all
    register-mode: interface
    qos-enable: false
  registry:
    address: ${BSIN_DOUBBO_REGISTRY_ADDRESS}
    username: ${BSIN_DOUBBO_REGISTRY_USERNAME}
    password: ${BSIN_DOUBBO_REGISTRY_PASSWORD}
  protocol:
    name: dubbo
    port: -1
  scan:
    base-packages: me.flyray.bsin.server.impl
  provider:
    validation: true
    version: dev
  consumer:
    check: false
    version: dev

dromara:
  x-file-storage: #文件存储配置
    default-platform: aliyun-oss-1 #默认使用的存储平台
    aliyun-oss:
      - platform: aliyun-oss-1 # 存储平台标识
        enable-storage: true  # 启用存储
        access-key: ${ALIYUN_ACCESS_KEY:your_access_key}
        secret-key: ${ALIYUN_SECRET_KEY:your_secret_key}
        end-point: ${ALIYUN_OSS_ENDPOINT:oss-cn-hangzhou.aliyuncs.com}
        bucket-name: ${ALIYUN_BUCKET_NAME:your_bucket_name}
        domain: ${ALIYUN_OSS_DOMAIN:https://your_bucket_name.oss-cn-hangzhou.aliyuncs.com/} # 访问域名，注意"/"结尾
        base-path: upload/ # 基础路径
        # STS配置（可选）
        sts:
          enabled: false  # 是否启用STS，默认false
          arn: ${ALIYUN_ROLE_ARN:acs:ram::your_account_id:role/your_role_name}  # 角色ARN
          role-session-name: bsin-oss-session  # 角色会话名称
          policy: |  # 策略文档（可选）
            {
              "Version": "1",
              "Statement": [
                {
                  "Effect": "Allow",
                  "Action": [
                    "oss:PutObject",
                    "oss:GetObject",
                    "oss:DeleteObject"
                  ],
                  "Resource": [
                    "acs:oss:*:*:your_bucket_name/*"
                  ]
                }
              ]
            }
          duration-seconds: 3600  # 临时凭证有效期（秒）