spring:
  #数据库配置
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${UPMS_MYSQL_DB_URL}?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
    username: ${UPMS_MYSQL_DB_USERNAME}
    password: ${UPMS_MYSQL_DB_PASSWORD}
  #redis
  redis:
    host: ${UPMS_REDIS_HOST}
    port: ${UPMS_REDIS_PORT}
    password: ${UPMS_REDIS_PASSWORD}
    database: ${UPMS_REDIS_DB}

shenyu:
  register:
    registerType: http #zookeeper #etcd #nacos #consul
    serverLists: ${SHENYU_REGISTER_SERVERLISTS} #localhost:2181 #http://localhost:2379 #localhost:8848
    props:
      username: ${SHENYU_REGISTER_PROPS_USERNAME}
      password: ${SHENYU_REGISTER_PROPS_PASSWORD}
  client:
    dubbo:
      props:
        contextPath: /upms
        appName: upms
    http:
      props:
        contextPath: /http
        appName: http

dubbo:
  application:
    name: ${spring.application.name}
    # 注册行为：应用级别  可选值 interface、instance、all
    register-mode: interface
    qos-enable: false
  registry:
    address: ${DOUBBO_REGISTRY_ADDRESS}
    username: ${DOUBBO_REGISTRY_USERNAME}
    password: ${DOUBBO_REGISTRY_ADDRESS}
  protocol:
    name: dubbo
    port: -1
  scan:
    base-packages: me.flyray.bsin.server.impl
  provider:
    validation: true
    version: dev
  consumer:
    check: false
    version: dev
  custom:
    log-level: full
    request-log: true

bsin:
  oss:
    upload:
      uploadPath: G:\/upload\/
    message:
      upPath: /home/leonard/ipfsfile/
      preImgUrl: http://file.s11edao.com
    ipfs:
      gateway: http://ipfs.s11edao.com/ipfs/
      api: http://ipfsadmin.s11edao.com/api/v0

dromara:
  x-file-storage: #文件存储配置
    default-platform: aliyun-oss-1 #默认使用的存储平台
    aliyun-oss:
      - platform: aliyun-oss-1 # 存储平台标识
        enable-storage: true  # 启用存储
        access-key: ??
        secret-key: ??
        end-point: ??
        bucket-name: ??
        domain: ?? # 访问域名，注意“/”结尾，例如：https://abc.oss-cn-shanghai.aliyuncs.com/
        base-path: test/ # 基础路径