package com.example.rules

global java.util.Map globalMap

rule "decision_rule_1_10"
    lock-on-active true
when
then
end

rule "decision_rule_1_11"
    lock-on-active true
when
then
    globalMap.put("userScore", "100");
    globalMap.put("validVip", "不是vip");
end

rule "decision_rule_1_12"
    lock-on-active true
when
then
    globalMap.put("userScore", "500");
    globalMap.put("validResult", "通过");
end

rule "decision_rule_1_13"
    lock-on-active true
when
then
    globalMap.put("userScore", "300");
end

