# 基础镜像
FROM openjdk:17-jdk-slim
# author
MAINTAINER bsin-paas

LABEL version=3.0.0

# 挂载目录
VOLUME /home/bsin-paas-os/server-apps/ali-ai-studio
# 创建目录
RUN mkdir -p /home/bsin-paas-os/server-apps/ali-ai-studio
# 指定路径
WORKDIR /home/bsin-paas-os/server-apps/ali-ai-studio
# 复制jar文件到路径
COPY ./jar/ali-ai-studio-server-3.0.0-SNAPSHOT.jar /home/bsin-paas-os/server-apps/ali-ai-studio/ali-ai-studio-server-3.0.0-SNAPSHOT.jar
# 启动用户服务
ENTRYPOINT ["java","-jar","ali-ai-studio-server-3.0.0-SNAPSHOT.jar"]
