# 基础镜像
FROM  openjdk:11
# author
MAINTAINER bsin-paas

LABEL version=2.0.0

# 挂载目录
VOLUME /home/bsin-paas-os/targe-gateway-admin
# 创建目录
RUN mkdir -p /home/bsin-paas-os/targe-gateway-admin
# 指定路径
WORKDIR /home/bsin-paas-os/targe-gateway-admin
# 复制jar文件到路径
COPY ./jar/targe-gateway-admin-server-2.0.0-SNAPSHOT.jar /home/bsin-paas-os/targe-gateway-admin/targe-gateway-admin-server-2.0.0-SNAPSHOT.jar
# 启动用户服务
ENTRYPOINT ["java","-jar","targe-gateway-admin-server-2.0.0-SNAPSHOT.jar"]
