# 基础镜像
FROM  openjdk:17
# author
MAINTAINER bsin-paas

LABEL version=2.0.0

# 挂载目录
VOLUME /home/bsin-paas-os/server-apps/http
# 创建目录
RUN mkdir -p /home/bsin-paas-os/server-apps/http
# 指定路径
WORKDIR /home/bsin-paas-os/server-apps/http
# 复制jar文件到路径
COPY ./jar/http-server-2.0.0-SNAPSHOT.jar /home/bsin-paas-os/server-apps/file/bsin-server-file-3.0.0-SNAPSHOT.jar
# 启动用户服务
ENTRYPOINT ["java","-jar","file-server-3.0.0-SNAPSHOT.jar"]
