# 基础镜像
FROM  openjdk:11
# author
MAINTAINER bsin-paas

LABEL version=2.0.0

# 挂载目录
VOLUME /home/bsin-paas-os/server-apps/aiAgent
# 创建目录
RUN mkdir -p /home/bsin-paas-os/server-apps/aiAgent
# 指定路径
WORKDIR /home/bsin-paas-os/server-apps/aiAgent
# 复制jar文件到路径
COPY ./jar/aiAgent-server-2.0.0-SNAPSHOT.jar /home/bsin-paas-os/server-apps/aiAgent/aiAgent-server-2.0.0-SNAPSHOT.jar
# 启动用户服务
ENTRYPOINT ["java","-jar","aiAgent-server-2.0.0-SNAPSHOT.jar"]
