
[app]
AppName = bsin-paas golang server
# 可以通过环境变量 GOLANG_SERVER_PREFIX_URL 覆盖此值
PrefixUrl = http://127.0.0.1:8125
RuntimeRootPath = runtime/
JwtSecret=123
PageSize=10

ImageSavePath = upload/images/
# MB
ImageMaxSize = 5
ImageAllowExts = .jpg,.jpeg,.png

ExportSavePath = export/
QrCodeSavePath = qrcode/
FontSavePath = fonts/

LogSavePath = logs/
LogSaveName = log
LogFileExt = log
TimeFormat = 20060102


[server]
AppName = mpc server
#debug or release
# 可以通过环境变量 GOLANG_SERVER_RUN_MODE 覆盖此值
RunMode = release
# 可以通过环境变量 GOLANG_SERVER_HTTP_PORT 覆盖此值
HttpPort = 8125
# 可以通过环境变量 GOLANG_SERVER_READ_TIMEOUT 覆盖此值
ReadTimeout = 6000
# 可以通过环境变量 GOLANG_SERVER_WRITE_TIMEOUT 覆盖此值
WriteTimeout = 6000
AccessToken = 123456

[database]
Type = mysql
User = root
Password = 123456
Host = 127.0.0.1:3316
Name = bsin-go
TablePrefix = mpc_

[mysql]
#Host = 127.0.0.1
Host = rm-2ze2tn8118l90v997no.mysql.rds.aliyuncs.com
Port = 3306
DBName = bsin-mpc
#Username = root
Username = flyray_eco
#Password = 123456
Password = bsin_paas_os123
SSLMode = disable
TimeZone = Asia/Ho_Chi_Minh

ConnectionMaxIdleTime = 10
ConnectionMaxLifetime = 30
MaxIdleConnections = 2
MaxOpenConnections = 5
LogLevel = info

[postgres]
Host = 127.0.0.1
Port = 5432
DBName = bsin-mpc
Username = root
Password = 123456
SSLMode = disable
TimeZone = Asia/Ho_Chi_Minh

ConnectionMaxIdleTime = 10
ConnectionMaxLifetime = 30
MaxIdleConnections = 2
MaxOpenConnections = 5
LogLevel = info

[redis] 
# 可以通过环境变量 GOLANG_SERVER_REDIS_ADDR 覆盖此值
Addr = 127.0.0.1:6379
# 可以通过环境变量 GOLANG_SERVER_REDIS_PASSWORD 覆盖此值
Password = 123456
# 可以通过环境变量 GOLANG_SERVER_REDIS_DB 覆盖此值
DB = 3 
# gredis
Host = 127.0.0.1:6379
MaxIdle = 30
MaxActive = 30
IdleTimeout = 200

[mpcClient]
; Clients = 0.0.0.0:8225, 0.0.0.0:8226
Clients = 0.0.0.0:8225, 0.0.0.0:8226, 0.0.0.0:8227, 0.0.0.0:8228
ClientNames = bsin-server-mpc-client1, bsin-server-mpc-client2, bsin-server-mpc-client3, bsin-server-mpc-client4
Ports = 8225, 8226, 8227, 8228
ServerUrl = ws://127.0.0.1:8125/api/v1/mpc/ws
#AccessToken = 123456


[rabbit]
Url = amqp://guest:guest@127.0.0.1:5672/
Timeout = 10
Enable = false

[oidc]
Issuer = 
CacheTTL = 
Audience = #[]string
ClaimsPath = 


[auth]
Domain = 
ClientId = 
ClientSecret =  
Key = 1234567887654321


[wechat] 
# 可以通过环境变量 GOLANG_SERVER_BSIN_BASE_URL 覆盖此值
BsinBaseUrl = http://127.0.0.1:9095
# 可以通过环境变量 GOLANG_SERVER_BSIN_CUSTOMER_TOKEN 覆盖此值
BsinCustomerToken = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYmYiOjE3MDM0MjkyNDMsInRlbmFudElkIjoiMTczNzg0MTI3NDI3MjIyMzIzMiIsImV4cCI6MTcwMzUxNTY0MywiaWF0IjoxNzAzNDI5MjQzLCJ1c2VybmFtZSI6IjE2Njc1NTg4MzgxIn0.50Ka741JX3tdV3BqgaFck5Eyn2v7khDUbl1PJQMXUuc
# 可以通过环境变量 GOLANG_SERVER_WECHAT_VERSION 覆盖此值
Version = 1.0
# 可以通过环境变量 GOLANG_SERVER_WECHAT_AUTO_PASS 覆盖此值
AutoPass = true 
# 可以通过环境变量 GOLANG_SERVER_WECHAT_AUTO_PASS_RESPONSE 覆盖此值
AutoPassResponse = 123456
# 可以通过环境变量 GOLANG_SERVER_WECHAT_SESSION_TIMEOUT 覆盖此值
SessionTimeout = 100
# 可以通过环境变量 GOLANG_SERVER_WECHAT_SESSION_CLEAR_TOKEN 覆盖此值
SessionClearToken = clear