# 基础镜像
FROM nacos/nacos-server:2.3.2

# author
MAINTAINER bsin-paas

# 创建目录
RUN mkdir -p /home/bsinpaas/docker/nacos

# 复制conf文件到路径
COPY ./conf/application.properties /home/bsinpaas/docker/nacos/conf/application.properties
