# 使用 Node.js 官方镜像作为基础镜像
FROM node:18.16.1 AS build
# 设置工作目录
WORKDIR /app
# 从宿主机复制 package.json 和 package-lock.json
COPY package*.json ./
# 安装依赖
RUN yarn
# 复制项目文件到工作目录
COPY . .
# 构建项目
RUN yarn build
# 使用 Nginx 官方镜像作为基础镜像
FROM nginx:alpine
# 从构建阶段复制构建结果到 Nginx 的默认静态文件目录
# 我们假设项目编译结果会存放到dist目录
# --from=build就是指定从这个阶段的文件中复制
COPY --from=build /app/dist /usr/share/nginx/html
# 暴露 Nginx 端口
EXPOSE 80
# 启动 Nginx
CMD ["nginx", "-g", "daemon off;"]
