server:
  port: 8114

spring:
  application:
    name: crm-server
#  profiles:
#    active: dev
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/exception_zh

# Nacos 配置
nacos:
  server-addr: 127.0.0.1:8848
  username: nacos
  password: nacos
  namespace:
  seata-namespace: public
  # Nacos 配置中心的配置项，对应 NacosConfigProperties 配置类
  config:
    server-addr: 127.0.0.1:8848 # Nacos 服务器地址
    namespace:
    username: nacos
    password: nacos
    bootstrap:
      enable: true # 是否开启 Nacos 配置预加载功能。默认为 false。
      log-enable: true # 是否开启 Nacos 支持日志级别的加载时机。默认为 false。
    data-ids: crm-dubbo.yml # 使用的 Nacos 配置集的 dataId。
    type: YAML # 使用的 Nacos 配置集的配置格式。默认为 PROPERTIES。
#    group: test # 使用的 Nacos 配置分组，默认为 DEFAULT_GROUP。


