spring:
  #数据库配置
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.198.198:3306/baiyetong-upms?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
  #redis
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 0
  task:
    execution:
      pool:
        core-size: 10
        max-size: 16                          # 默认是 Integer.MAX_VALUE
        keep-alive: 60s                       # 当线程池中的线程数量大于 corePoolSize 时，如果某线程空闲时间超过keepAliveTime，线程将被终止
        allow-core-thread-timeout: true       # 是否允许核心线程超时,默认true
        queue-capacity: 100                   # 线程队列的大小,默认Integer.MAX_VALUE
      shutdown:
        await-termination: false              # 线程关闭等待
      thread-name-prefix: task-

shenyu:
  register:
    registerType: http #zookeeper #etcd #nacos #consul
    serverLists: http://127.0.0.1:9095 #localhost:2181 #http://localhost:2379 #localhost:8848
    props:
      username: admin
      password: 123456
  client:
    dubbo:
      props:
        contextPath: /crm
        appName: crm
  security:
    authentication-secretKey: shenyu-test-shenyu-test-shenyu-test

dubbo:
  application:
    name: ${spring.application.name}
    # 注册行为：应用级别  可选值 interface、instance、all
    register-mode: interface
    qos-enable: false
  registry:
    address: nacos://127.0.0.1:8848
    username: nacos
    password: nacos
  protocol:
    name: dubbo
    port: -1
  scan:
    base-packages: me.flyray.bsin.server.impl
  provider:
    validation: true
    version: dev
  consumer:
    check: false
    version: dev

