logging:
  level:
    org.springframework.web: INFO
    com.github.binarywang.demo.wx.mp: DEBUG
    me.chanjar.weixin: DEBUG

chatGPT:
  templateEnable: false #是否启用模板推送消息

shenyu:
  register:
    registerType: http #zookeeper #etcd #nacos #consul
    serverLists: http://127.0.0.1:9095 #localhost:2181 #http://localhost:2379 #localhost:8848
    props:
      username: admin
      password: 123456
  client:
    dubbo:
      props:
        contextPath: /crm
        appName: crm

dubbo:
  application:
    name: ${spring.application.name}
    # 注册行为：应用级别  可选值 interface、instance、all
    register-mode: interface
    qos-enable: false
  registry:
    address: nacos://127.0.0.1:8848
    username: nacos
    password: nacos
  protocol:
    name: dubbo
    port: -1
  scan:
    base-packages: me.flyray.bsin.server.impl
  provider:
    validation: true
    version: dev
  consumer:
    check: false
    version: dev

wx:
  mp:
    useRedis: false
    redisConfig:
      host: 127.0.0.1
      port: 6379
    configs:
      - appId: 11 # 第一个公众号的appid
        secret: 11 # 公众号的appsecret
        token: 11 # 接口配置里的Token值
        aesKey: 11 # 接口配置里的EncodingAESKey值
      - appId: 2222 # 第二个公众号的appid，以下同上
        secret: 1111
        token: 111
        aesKey: 111

--- # redis 单机配置(单机与集群只能开启一个另一个需要注释掉)
spring:
  redis:
    # 地址
    host: 127.0.0.1
    # host: 192.168.198.198
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 10
    # 密码(如没有密码请注释掉)
    # password: hongrenwang123
    password: 123456
    # password: hongrenwang123
    # 连接超时时间
    timeout: 10s
    # 是否开启ssl
    ssl: false

redisson:
  # redis key前缀
  keyPrefix:
  # 线程池数量
  threads: 4
  # Netty线程池数量
  nettyThreads: 8
  # 单节点配置
  singleServerConfig:
    # 客户端名称
    clientName: name
    # 最小空闲连接数
    connectionMinimumIdleSize: 8
    # 连接池大小
    connectionPoolSize: 32
    # 连接空闲超时，单位：毫秒
    idleConnectionTimeout: 10000
    # 命令等待超时，单位：毫秒
    timeout: 3000
    # 发布和订阅连接池大小
    subscriptionConnectionPoolSize: 50

sms:
  # 标注从yml读取配置
  config-type: yaml
  blends:
    # 自定义的标识，也就是configId这里可以是任意值（最好不要是中文）
    tx1:
      #厂商标识，标定此配置是哪个厂商，详细请看厂商标识介绍部分
      supplier: tencent
      #您的accessKey
      access-key-id: 您的accessKey
      #您的accessKeySecret
      access-key-secret: 您的accessKeySecret
      #您的短信签名
      signature: 您的短信签名
      #模板ID 非必须配置，如果使用sendMessage的快速发送需此配置
      template-id: xxxxxxxx
      #您的sdkAppId
      sdk-app-id: 您的sdkAppId
      # 自定义的标识，也就是configId这里可以是任意值（最好不要是中文）
    tx2:
      #厂商标识，标定此配置是哪个厂商，详细请看厂商标识介绍部分
      supplier: tencent
      #您的accessKey
      access-key-id: 您的accessKey
      #您的accessKeySecret
      access-key-secret: 您的accessKeySecret
      #您的短信签名
      signature: 您的短信签名
      #模板ID 非必须配置，如果使用sendMessage的快速发送需此配置
      template-id: xxxxxxxx
      #您的sdkAppId
      sdk-app-id: 您的sdkAppId
