#日志
logging:
  level:
    me.flyray.bsin: DEBUG
    org.springframework: DEBUG
    org.springframework.io: DEBUG
    com.github.binarywang.demo.wx.mp: DEBUG
    me.chanjar.weixin: DEBUG
    io.modelcontextprotocol.client: DEBUG
    io.modelcontextprotocol.spec: DEBUG

chatGPT:
  templateEnable: false #是否启用模板推送消息

shenyu:
  register:
    registerType: http #zookeeper #etcd #nacos #consul
    serverLists: ${BSIN_SHENYU_REGISTER_SERVERLISTS} #localhost:2181 #http://localhost:2379 #localhost:8848
    props:
      username: ${BSIN_SHENYU_REGISTER_PROPS_USERNAME}
      password: ${BSIN_SHENYU_REGISTER_PROPS_PASSWORD}
  client:
    dubbo:
      props:
        contextPath: /crm
        appName: crm

dubbo:
  application:
    name: ${spring.application.name}
    # 注册行为：应用级别  可选值 interface、instance、all
    register-mode: interface
    qos-enable: false
  registry:
    address: ${BSIN_DOUBBO_REGISTRY_ADDRESS}
    username: ${BSIN_DOUBBO_REGISTRY_USERNAME}
    password: ${BSIN_DOUBBO_REGISTRY_PASSWORD}
  protocol:
    name: dubbo
    port: -1
  scan:
    base-packages: me.flyray.bsin.server.impl
  provider:
    validation: true
    version: dev
  consumer:
    check: false
    version: dev

wx:
  mp:
    useRedis: false
    redisConfig:
      host: ${CRM_REDIS_HOST}
      port: ${CRM_REDIS_PORT}
    configs:
      - appId: 11 # 第一个公众号的appid
        secret: 11 # 公众号的appsecret
        token: 11 # 接口配置里的Token值
        aesKey: 11 # 接口配置里的EncodingAESKey值
      - appId: 2222 # 第二个公众号的appid，以下同上
        secret: 1111
        token: 111
        aesKey: 111
  config-storage:
    redis:
      host: ${CRM_REDIS_HOST}
      port: ${CRM_REDIS_PORT}
      password: ${CRM_REDIS_PASSWORD}
--- # redis 单机配置(单机与集群只能开启一个另一个需要注释掉)

# redis配置 -使用时需要配置自己的redis

spring:
  data:
    redis:
      host: ${CRM_REDIS_HOST}
      port: ${CRM_REDIS_PORT}
      password: ${CRM_REDIS_PASSWORD}
  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE}
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      chat:
        options:
          stream: true
          model: qwen-turbo
    mcp:
      server:
        name: crm-mcp-server
        version: 1.0.0
        type: ASYNC  # Recommended for reactive applications
        instructions: "This reactive server provides time information tools and resources"
        sse-message-endpoint: /mcp/messages
        capabilities:
          tool: true
          resource: true
          prompt: true
          completion: true
    # 配置mcp nacos
    alibaba:
      mcp:
        nacos:
#          namespace: 142f0696-b004-45ca-ae95-0b17dc3496f5
          namespace: ${BSIN_NACOS_NAMESPACE}
          server-addr: ${BSIN_NACOS_SERVER_ADDR}
          username: ${BSIN_NACOS_USERNAME}
          password: ${BSIN_NACOS_PASSWORD}
          registry:
            enabled: true
            service-group: mcp-server
            service-name: crm-mcp-server

redisson:
  # redis key前缀
  keyPrefix:
  # 线程池数量
  threads: 4
  # Netty线程池数量
  nettyThreads: 8
  # 单节点配置
  singleServerConfig:
    # 客户端名称
    clientName: name
    # 最小空闲连接数
    connectionMinimumIdleSize: 8
    # 连接池大小
    connectionPoolSize: 32
    # 连接空闲超时，单位：毫秒
    idleConnectionTimeout: 10000
    # 命令等待超时，单位：毫秒
    timeout: 3000
    # 发布和订阅连接池大小
    subscriptionConnectionPoolSize: 50

sms:
  alibaba:
    #阿里云的accessKey
    accessKeyId: 您的accessKey
    #阿里云的accessKeySecret
    accessKeySecret: 您的accessKeySecret
    #短信签名
    signature: 测试签名
    #模板ID 用于发送固定模板短信使用
    templateId: SMS_215125134
    #模板变量 上述模板的变量
    templateName: code
    #请求地址 默认为dysmsapi.aliyuncs.com 如无特殊改变可以不用设置
    requestUrl: dysmsapi.aliyuncs.com
  huawei:
    #华为短信appKey
    appKey: 5N6fvXXXX920HaWhVXXXXXX7fYa
    #华为短信appSecret
    app-secret: Wujt7EYzZTBXXXXXXEhSP6XXXX
    #短信签名
    signature: 华为短信测试
    #通道号
    sender: 8823040504797
    #模板ID 如果使用自定义模板发送方法可不设定
    template-id: acXXXXXXXXc274b2a8263479b954c1ab5
    #华为回调地址，如不需要可不设置或为空
    statusCallBack:
    #华为分配的app请求地址
    url: https://XXXXX.cn-north-4.XXXXXXXX.com:443


bsin:
  supersTenantId: 6345824413764157440
  security:
    authentication-secretKey: shenyu-test-shenyu-test-shenyu-test
    # 过期时间，单位分钟
    authentication-expiration: 60
  pay:
    approveOper:
      privateKey: 11
    chainEnv: 11
    contractAddress: 22
  oss:
    upload:
      uploadPath: G:\/upload\/
    message:
      upPath: /home/leonard/ipfsfile/
      preImgUrl: http://file.s11edao.com
    ipfs:
      gateway: http://ipfs.s11edao.com/ipfs/
      api: http://ipfsadmin.s11edao.com/api/v0

dromara:
  x-file-storage: #文件存储配置
    default-platform: ${DROMARA_X_FILE_STORAGE_DEFAULT_PLATFORM} #默认使用的存储平台
    aliyun-oss:
      - platform: ${ALIYUN_OSS_PLATFORM} # 存储平台标识
        enable-storage: true  # 启用存储
        access-key: ${ALIYUN_OSS_ACCESS_KEY}
        secret-key: ${ALIYUN_OSS_SECRET_KEY}
        end-point: ${ALIYUN_OSS_ENDPOINT}
        bucket-name: ${ALIYUN_OSS_BUCKET_NAME}
        domain: ${ALIYUN_OSS_DOMAIN} # 访问域名，注意“/”结尾，例如：https://abc.oss-cn-shanghai.aliyuncs.com/
        base-path: ${ALIYUN_OSS_BASE_PATH} # 基础路径
        sts:
          arn: ${ALIYUN_OSS_STS_ARM}