# 基础镜像
FROM emqx/emqx:5.8.2
# author
MAINTAINER bsin-paas

# 挂载目录
VOLUME /home/bsin-paas-os/middleware/emqx
## 创建目录
# RUN mkdir -p /home/bsin-paas-os/middleware/emqx

# RUN mkdir -p /opt/emqx/data/configs

## 指定路径
WORKDIR /home/bsin-paas-os/middleware/emqx
