spring:
  #数据库配置
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-2zeq9708apq292r36ko.mysql.rds.aliyuncs.com:3306/bsin-intelligent-decision?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: root

  #redis
  redis:
    host: 127.0.0.1
    port: 6379
    password: root
    database: 123456

dubbo:
  application:
    name: ${spring.application.name}
    # 注册行为：应用级别  可选值 interface、instance、all
    register-mode: interface
    qos-enable: false
  registry:
    address: nacos://127.0.0.1:8848
    username: nacos
    password: nacos
  protocol:
    name: dubbo
    port: -1
  scan:
    base-packages: me.flyray.bsin.server.impl
  provider:
    validation: true
    version: dev
  consumer:
    check: false
    version: dev
  custom:
    log-level: full
    request-log: true

