spring:
  #数据库配置
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${BRMS_MYSQL_DB_URL}?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
    username: ${BRMS_MYSQL_DB_USERNAME}
    password: ${BRMS_MYSQL_DB_PASSWORD}

  #redis
  redis:
    host: ${BRMS_REDIS_HOST}
    port: ${BRMS_REDIS_PORT}
    password: ${BRMS_REDIS_PASSWORD}
    database: ${BRMS_REDIS_DB}

dubbo:
  application:
    name: ${spring.application.name}
    # 注册行为：应用级别  可选值 interface、instance、all
    register-mode: interface
    qos-enable: false
  registry:
    address: ${DOUBBO_REGISTRY_ADDRESS}
    username: ${DOUBBO_REGISTRY_USERNAME}
    password: ${DOUBBO_REGISTRY_ADDRESS}
  protocol:
    name: dubbo
    port: -1
  scan:
    base-packages: me.flyray.bsin.server.impl
  provider:
    validation: true
    version: dev
  consumer:
    check: false
    version: dev
  custom:
    log-level: full
    request-log: true

