server:
  port: 9103

spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev
  messages:
    encoding: utf-8
    # 国际化资源文件路径（配置文件路径）
    basename: i18n/exception
  application:
    name: scaffold

# Nacos 配置
nacos:
  server-addr: 127.0.0.1:8848
  username: nacos
  password: nacos
  namespace:
  seata-namespace: public
  # Nacos 配置中心的配置项，对应 NacosConfigProperties 配置类
  config:
    server-addr: 127.0.0.1:8848 # Nacos 服务器地址
    namespace:
    username: nacos
    password: nacos
    bootstrap:
      enable: false # 是否开启 Nacos 配置预加载功能。默认为 false。
      log-enable: true # 是否开启 Nacos 支持日志级别的加载时机。默认为 false。
    data-ids: scaffold-test.yml # 使用的 Nacos 配置集的 dataId。
    type: YAML # 使用的 Nacos 配置集的配置格式。默认为 PROPERTIES。
#    group: test # 使用的 Nacos 配置分组，默认为 DEFAULT_GROUP。

#日志
logging:
  level:
    me.flyray.bsin: debug
    org.springframework: warn

rocketmq:
  consumer:
    access-key: rocketmq2
    secret-key: 12345678
    group: consumer_group
    # 一次拉取消息最大值，注意是拉取消息的最大值而非消费最大值
    pull-batch-size: 10
    topic: waas-test
  name-server: 127.0.0.1:9876
  producer:
    access-key: rocketmq2
    secret-key: 12345678
    # 发送同一类消息的设置为同一个group，保证唯一
    group: springboot_producer_group
    # 发送消息超时时间，默认3000
    sendMessageTimeout: 10000
    # 发送消息失败重试次数，默认2
    retryTimesWhenSendFailed: 2
    # 异步消息重试此处，默认2
    retryTimesWhenSendAsyncFailed: 2
    # 消息最大长度，默认1024 * 1024 * 4(默认4M)
    maxMessageSize: 4096
    # 压缩消息阈值，默认4k(1024 * 4)
    compressMessageBodyThreshold: 4096
    # 是否在内部发送失败时重试另一个broker，默认false
    retryNextServer: false

