FROM openjdk:8-jdk-alpine

ARG NACOS_VERSION=2.4.2

RUN wget  && \
    unzip nacos-server-${NACOS_VERSION}.zip && \
    mv nacos-server-${NACOS_VERSION} /nacos && \
    rm nacos-server-${NACOS_VERSION}.zip && \
    echo '#!/bin/sh' > /start-nacos.sh && \
    echo 'sh /nacos/bin/startup.sh -m standalone' >> /start-nacos.sh && \
    chmod +x /start-nacos.sh && \
    rm -rf /nacos/conf

ENTRYPOINT ["/start-nacos.sh"]