// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import model_2 from 'D:/bolei-workspace/bsin-paas-os/bsin-ui-apps/bsin-ui-ai/src/.umi/plugin-qiankun-slave/qiankunModel';
import { useQiankunStateForSlave as model_1 } from 'D:/bolei-workspace/bsin-paas-os/bsin-ui-apps/bsin-ui-ai/src/app';

export const models = {
model_2: { namespace: '@@qiankunStateFromMaster', model: model_2 },
model_1: { namespace: '@@qiankunStateForSlave', model: model_1 },
} as const
