// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import model_1 from 'D:/bolei-workspace/bsin-paas-os/bsin-ui-apps/bsin-ui-ai/src/.umi/plugin-qiankun-slave/qiankunModel';

export const models = {
model_1: { namespace: '@@qiankunStateFromMaster', model: model_1 },
} as const
