// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/","parentId":"@@/global-layout","id":"1"},"2":{"path":"/","redirect":"/home","parentId":"1","id":"2"},"3":{"path":"/home","parentId":"1","id":"3"},"4":{"path":"/ai-llm","parentId":"1","id":"4"},"5":{"path":"/ai-embedding-model","parentId":"1","id":"5"},"6":{"path":"/ai-chunk-model","parentId":"1","id":"6"},"7":{"path":"/ai-prompt-template","parentId":"1","id":"7"},"8":{"path":"ai-flow","parentId":"1","id":"8"},"9":{"path":"/ai-copilot","parentId":"1","id":"9"},"10":{"path":"/ai-tool","parentId":"1","id":"10"},"11":{"path":"/ai-agent","parentId":"1","id":"11"},"12":{"path":"/ai-knowledge-base","parentId":"1","id":"12"},"13":{"path":"/ai-chat","parentId":"1","id":"13"},"14":{"path":"/ai-sensitive-words","parentId":"1","id":"14"},"15":{"path":"/ai-member","parentId":"1","id":"15"},"16":{"path":"/ai-setting","parentId":"1","id":"16"},"17":{"path":"/ai-admin-monitor","parentId":"1","id":"17"},"18":{"path":"/userCenter","parentId":"1","id":"18"},"@@/global-layout":{"id":"@@/global-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import(/* webpackChunkName: "layouts__index" */'@/layouts/index.tsx')),
'2': React.lazy(() => import( './EmptyRoute')),
'3': React.lazy(() => import(/* webpackChunkName: "p__Home__index" */'@/pages/Home/index.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__LLM__index" */'@/pages/LLM/index.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__EmbeddingModel__index" */'@/pages/EmbeddingModel/index.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__ChunkModel__index" */'@/pages/ChunkModel/index.tsx')),
'7': React.lazy(() => import(/* webpackChunkName: "p__PromptTemplate__index" */'@/pages/PromptTemplate/index.tsx')),
'8': React.lazy(() => import(/* webpackChunkName: "p__Flow__index" */'@/pages/Flow/index.tsx')),
'9': React.lazy(() => import(/* webpackChunkName: "p__Copilot__index" */'@/pages/Copilot/index.tsx')),
'10': React.lazy(() => import(/* webpackChunkName: "p__Tool__index" */'@/pages/Tool/index.tsx')),
'11': React.lazy(() => import(/* webpackChunkName: "p__Agent__index" */'@/pages/Agent/index.tsx')),
'12': React.lazy(() => import(/* webpackChunkName: "p__KnowledgeBase__index" */'@/pages/KnowledgeBase/index.tsx')),
'13': React.lazy(() => import(/* webpackChunkName: "p__Chat__index" */'@/pages/Chat/index.tsx')),
'14': React.lazy(() => import(/* webpackChunkName: "p__SensitiveWords__index" */'@/pages/SensitiveWords/index.tsx')),
'15': React.lazy(() => import(/* webpackChunkName: "p__Member__index" */'@/pages/Member/index.tsx')),
'16': React.lazy(() => import(/* webpackChunkName: "p__Setting__index" */'@/pages/Setting/index.tsx')),
'17': React.lazy(() => import(/* webpackChunkName: "p__AdminMonitor__index" */'@/pages/AdminMonitor/index.tsx')),
'18': React.lazy(() => import(/* webpackChunkName: "p__Setting__index" */'@/pages/Setting/index.tsx')),
'@@/global-layout': React.lazy(() => import(/* webpackChunkName: "layouts__index" */'D:/bolei-workspace/bsin-paas-os/bsin-ui-apps/bsin-ui-ai/src/layouts/index.tsx')),
},
  };
}
