# 基础镜像
FROM mysql:8.0

# author
MAINTAINER bsin-paas

# 挂载目录
VOLUME /home/bsin-paas-os/middleware/mysql
# 创建目录
RUN mkdir -p /home/bsin-paas-os/middleware/mysql
# 指定路径
WORKDIR /home/bsin-paas-os/middleware/mysql
